version: '3.8'

services:

  # sudo docker compose exec app go run ./cli migrate
  # sudo docker compose exec app go run ./cli createadmin -e
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    volumes:
      - repos:/data/repos

  # use host.docker.internal as localhost for docker desktop
  # https://docs.docker.com/desktop/windows/networking/
  db:
    image: postgres:14.0-alpine
    volumes:
      - quizdb:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  # https://geshan.com.np/blog/2022/01/redis-docker/
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - quizredis:/data

volumes:
  quizdb:
  quizredis:
  repos:
